replicaCount: 2

frontend:
  image:
    repository: "REPLACE_WITH_FRONTEND_IMAGE"
    tag: "latest"
  service:
    port: 80
    targetPort: 3000

backend:
  image:
    repository: "REPLACE_WITH_BACKEND_IMAGE"
    tag: "latest"
  service:
    port: 8080
    targetPort: 8080

ingress:
  enabled: true
  host: api.internal
  path: /api
